[package]
name = "bingwallpaper"
version = "1.6.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "gzip"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
configparser = "3.1"
log = "0.4"
env_logger = "0.11"
chrono = { version = "0.4", features = ["serde"] }
rusqlite = { version = "0.32", features = ["bundled"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
    "Win32_UI_WindowsAndMessaging",
] }
windows-registry = "0.6"

[profile.release]
opt-level = 3
lto = true
strip = true
panic = "abort"
