[Daemon]
background = false
foreground = false
interval = 2

[Download]
country = auto
market =
keep_file_name = false
size_mode = prefer
collect =
image_size =
offset = 0
redownload = false
output_folder = C:\Users\YOUR_NAME\MyBingWallpapers
server = global
customserver =

[Proxy]
proxy_server =
proxy_port = 80
proxy_username =
proxy_password =

[Setter]
setter = win
setter_args =

[Database]
database_file =
database_no_image = false

[Debug]
debug = 0
